export const GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS";
export const GET_TODOS_LOADING = "GET_TODOS_LOADING";
export const GET_TODOS_FAILURE = "GET_TODOS_FAILURE";

export const ADD_TODOS_SUCCESS = "ADD_TODOS_SUCCESS";
export const ADD_TODOS_LOADING = "ADD_TODOS_LOADING";
export const ADD_TODOS_FAILURE = "ADD_TODOS_FAILURE";
